### ISSUE TITLE
Bug tracker back-end

### ISSUE THREAD

**Issue by coillarach** [Dandelion-dev-team/dandelion#107]
Requires additional table: ISSUE. See ER diagram

Routes:

* POST new issue: /issue
* GET all issues: /issue
* GET one issue: /issue/&lt;issue_id&gt;
* PUT update details: /issue/&lt;issue_id&gt;
* PUT add note: /issue/note/&lt;issue_id&gt;
* PUT close issue: /issue/close/&lt;issue_id&gt;
* POST image: /issue/upload_image/&lt;issue_id&gt;

A screenshot may be optionally uploaded with a new issue. 
This means another object type under CONTENT_ROOT_UPLOAD/image of *issue*

# -Readiness-

## Any database changes are identified and documented

- [x] New ISSUE table created

## Any dependencies/impacts are identified and documented

Files that I will be working on:

- [x] admin/views/issue.py
- [x] models/issue.py
- [x] database new table

## The issue has been elaborated

The following routes has  been created and working:

- [x]  POST new issue: /issue
- [x]  GET all issues: /issue
- [x]  GET one issue: /issue/&lt;issue_id&gt;
- [x]  PUT update details: /issue/&lt;issue_id&gt;
- [x]  PUT add note: /issue/note/&lt;issue_id&gt;
- [x]  PUT close issue: /issue/close/&lt;issue_id&gt;
- [x]  POST image: /issue/upload_image/&lt;issue_id&gt;

- [ ] A screenshot may be optionally uploaded with a new issue. Another object type under CONTENT_ROOT_UPLOAD/image of *issue*

## Each task is testable

- [ ] Unit testing

## Each task is feasible
 
- [x] Yes

## Development environment is up-to-date

- [x] Yes

## All existing tests pass

- [ ] Yes

## Development branch is created

- [x] bug_tracker_back_end(Branch)

## Readiness has been documented
